Algoritmo "Entrada de dados"

Var

  idade : inteiro
  salario1, salario2 : real
  nome : caractere
  
Inicio

  escreva("Digite seu nome: ")
  leia(nome)
  escreva("Digite sua idade: ")
  leia(idade)
  escreva("Digite seu primeiro salário: ")
  leia(salario1)
  escreva("Digite seu segundo salário: ")
  leia(salario2)
  escreval()
  
  escreval("DADOS DIGITADOS")
  escreval("Nome = ", nome)
  escreval("Idade = ", idade)
  escreval("Salário = ", salario1 + salario2)

Fimalgoritmo