Algoritmo "idades"

Var

  nome1, nome2 : caractere
  idade1, idade2 : inteiro
  media : real

Inicio

  escreva ("Digite seu nome: ")
  leia(nome1)
  escreva("Digite sua idade: ")
  leia(idade1)
  escreva("Digite seu nome: ")
  leia(nome2)
  escreva("Digite sua idade: ")
  leia(idade2)
  
  media <- (idade1 + idade2)/2
  
  escreval()
  escreva("A idade media de ", nome1, " e ", nome2," é de ", media, " anos.")

Fimalgoritmo